// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Provides AI-powered budget suggestions based on user income and spending habits.
 *
 * @name aiPoweredBudgetSuggestions
 * @description This flow analyzes user financial data to suggest realistic and effective budgets.
 *
 * @interface AIPoweredBudgetSuggestionsInput
 * @description Input parameters for the aiPoweredBudgetSuggestions function.
 *
 * @interface AIPoweredBudgetSuggestionsOutput
 * @description Output containing AI-powered budget suggestions.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AIPoweredBudgetSuggestionsInputSchema = z.object({
  income: z.number().describe('Monthly income of the user.'),
  spendingHabits: z.string().describe('Description of the user\'s spending habits and categories.'),
});

export type AIPoweredBudgetSuggestionsInput = z.infer<typeof AIPoweredBudgetSuggestionsInputSchema>;

const AIPoweredBudgetSuggestionsOutputSchema = z.object({
  suggestedBudgets: z
    .string()
    .describe(
      'AI-powered budget suggestions for different spending categories based on user income and spending habits.'
    ),
});

export type AIPoweredBudgetSuggestionsOutput = z.infer<typeof AIPoweredBudgetSuggestionsOutputSchema>;

export async function aiPoweredBudgetSuggestions(
  input: AIPoweredBudgetSuggestionsInput
): Promise<AIPoweredBudgetSuggestionsOutput> {
  return aiPoweredBudgetSuggestionsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'aiPoweredBudgetSuggestionsPrompt',
  input: {
    schema: AIPoweredBudgetSuggestionsInputSchema,
  },
  output: {
    schema: AIPoweredBudgetSuggestionsOutputSchema,
  },
  prompt: `You are a financial advisor providing budget suggestions based on income and spending habits.

  Based on the user's monthly income: {{income}}
  And spending habits: {{spendingHabits}}

  Provide a detailed breakdown of suggested budget allocations for various categories, such as housing, food, transportation, entertainment, and savings. Be realistic and practical, and also suggest any areas where the user can cut costs or save more.
  Ensure that the suggested budgets are in alignment with the user's financial goals and promote financial well-being.
  Output should be a string.
  `,
});

const aiPoweredBudgetSuggestionsFlow = ai.defineFlow(
  {
    name: 'aiPoweredBudgetSuggestionsFlow',
    inputSchema: AIPoweredBudgetSuggestionsInputSchema,
    outputSchema: AIPoweredBudgetSuggestionsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
